services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb-container
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js  # Optional: must not rely on noauth
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
    external: true
